### ISSUE TITLE
gm_menu

### ISSUE THREAD

**Issue by SilentSpike** [SilentSpike/ACE3#2]
This issue will be frequently updated to track progress and new developments.

Situation
--
Branch: SilentSpike/gm_menu

* It's messy as fuck at the moment, but I've started work on introducing a new interaction menu alongside the existing self/interact menu.
* Compilation should be functional, it's hardcoded to use class `ACE_MasterActions` at the moment with the variables in the format `MasterAct_%1`. This could change with the generalization of #1365
* Using `Shift + G` as default key currently, the key handling should all be correct. ~~Using `interact_menu` for KeyUp as code shouldn't need changes.~~
* Rendering is semi-functional (in that it doesn't error badly) but that's where the majority of the mess is. My focus is to:
  - [x] Get it working in the default player view first
  - [x] Working when in a vehicle (which is technically a self interact, however should be able to use the same actions as far as I know)

TODO
--
Now that I've transferred all the code and got it working as desired I can work on the new changes:
- [x] Tweak compilation to use object name for base level action (no need for MainActions class)
- [x] ~~Use cursor position for rendering reference point rather than player position~~
- [x] Rendering in the curator view
  - [x] Add keyUp/keyDown EHs to curator display `312`
  - [x] ~~Make interaction seamless (don't close curator display if possible)~~
  - [x] ~~Use the curator cursor position as ref point~~
- [x] ~~Rendering in curator map view?~~
- [x] Self action when in curator unit first person view (not the same as remote control)
- [x] Fix weird rendering inconsistency (actions aren't always rendered when they should be)
- [ ] Implement menu access restriction
- [ ] Implement contextual compilation
- [ ] Clean up redundant code
- [ ] Add more actions

Errors
--
* ~~Worth noting that currently this does break the default interaction menus, I suspect that's just a result of the variables not being correctly handled everywhere yet and will resolve itself once the new menu is in a fully working state.~~ - 2015-05-24
* ~~There's currently an issue with `fnc_renderIcon` (which I'm just calling from the interact_menu addon as the code shouldn't need any changes) where the `_ctrl` variable likely isn't being correctly set elsewhere.~~ - 2015-05-28

**Comment by SilentSpike** [comment]
Alright, removed any kind of dependency on interact_menu for the time being. Once rendering is working correctly I can worry about refining things there.

**Comment by SilentSpike** [comment]
After being lost as to what the problem was for a while I finally remember that the existing code was presuming the settings variables were already set and I had to change the copied code to use EGVAR.

9541130ae5481c650a73f33e9f0334f4d273741c takes care of this nicely and the menu is now functional. However the action text doesn't seem to be displayed, will need to check that out.

**Comment by esteldunedain** [comment]
:+:1

**Comment by SilentSpike** [comment]
@esteldunedain Do you know off hand where the AlwaysUseCursorInteraction setting is checked? Doing a search of all the functions doesn't turn it up for me

**Comment by esteldunedain** [comment]
> @esteldunedain Do you know off hand where the AlwaysUseCursorInteraction setting is checked? Doing a search of all the functions doesn't turn it up for me

On fnc_keyDown.sqf, line 38

**Comment by SilentSpike** [comment]
Cursor menu support working. Now to figure out why the action display names aren't showing. :)

**Comment by SilentSpike** [comment]
cc2f73272fe0e44fe3924f9a1eb92eaff2d07265 Fixes the text. I think I'll actually take a look at cutting down on duplicate code before I go on to tweak the rendering. Now that everything works as expected progress should be much quicker.

**Comment by SilentSpike** [comment]
Well, I thought the stupid renderIcon error was gone, but it's back:

```
_ctrl ctrlSetPosition _pos;
_ctrl ctrlCommit 0>
17:48:41   Error position: <ctrlSetPosition _pos;
_ctrl ctrlCommit 0>
17:48:41   Error Type Number,Not a Number, expected Number
17:48:41 File z\ace\addons\gm_menu\functions\fnc_renderIcon.sqf, line 44
17:48:41 Error in expression <_cursorPos select 1) + 0.5)];
};
```

Who knows what's causing it. It wasn't there a minute ago and the only change I made since was to remove the setupTextColors function and change renderMenu to use `EGVAR(interact_menu,textSettingsMatrix)` and `EGVAR(interact_menu,colorSelectedSettings)`. Seemingly unrelated thing, but something's fucking up.

**Comment by SilentSpike** [comment]
@esteldunedain That one error mentioned above is a real thorn in my side. Did you guys happen to encounter it with the interact menu at all? (Or have any idea what's causing the issue)

**Comment by SilentSpike** [comment]
Fixed that stupid ass error. Accidentally reverted some EGVARs in a different function altogether and somehow created a weird numerical situation where ctrlSetPos was being passed some odd data it didn't expect.

**Comment by SilentSpike** [comment]
It might prove difficult to get the cursor position (in game view) to use as a reference point, so I might just have to continue using the player position except with a large distance and a much smaller FOV to scan (to balance performance)

**Comment by SilentSpike** [comment]
Documenting for easy reference:
* All the curator 3D/2D icons are stored in the curator logic variable `bis_fnc_addcuratoricon` in the format: [icon, show2D, show3D]. Icon uses the [drawIcon3D](https://community.bistudio.com/wiki/drawIcon3D) format.

**Comment by SilentSpike** [comment]
If I can get the position of the curator cursor (there must be a way using EHs, it'd be so convenient). Then I can just use screenToWorld like in the default view.

**Comment by SilentSpike** [comment]
[Progress!](https://gfycat.com/BetterWellwornBaleenwhale) :fireworks:

**Comment by esteldunedain** [comment]
@SilentSpike, that looks almost perfect! Congrats.

The Zeus submenu seems superfluous at first glance though, but that's easily fixable.

**Comment by SilentSpike** [comment]
There's some potential tweaking to be made to the rendering reference point and behavior still, but the bulk of it's all there now

**Comment by SilentSpike** [comment]
The rendering oddities I was experiencing were due to the occlusion code at the bottom of `fnc_renderActionsPoints`. I've commented out the code for now, it doesn't particularly apply to the GM menu based on the distances it's being used it

**Comment by SilentSpike** [comment]
Unsure of the best method of limiting access to the GM menu.

I asked around for some input on what's convenient:
* Module where list of units/UIDs can be provided
* Setting to let assigned zeus players automatically gain access

**Comment by SilentSpike** [comment]
So, I had a bit of a spur of inspiration the other day after feeling like the GM menu isn't all that practical now that it's working and I've tested it.

A quote from slack:
>So, instead of a fully fledged gm menu, what if using the interact key in zeus brought up a self-interact menu to control all currently selected objects/waypoints/groups etc. ?

>This has a couple advantages:
1. Less context ambiguity, you know exactly what the user wants to interact with
2. Can actually interact with groups/waypoints directly (the current implementation makes it near impossible to reliably do that)
3.  Ease of use, the menu is static, can be used easily on moving objects

>As for having it limited to the zeus interface, I don't see it as much of a trade-off as the practicality of the current implementation both inside/outside the zeus interface isn't that great

>Yet it still solves the original problem of being able to quickly change the attributes of groups/waypoints on the fly :)

>I'm going to start working on a basic mock-up as I feel like this approach has much more potential at the minor trade-off of being more focused

**Comment by esteldunedain** [comment]
Please do that on a sepparate branch; tbh conceptually I like the former idea much more, although I really haven't tested as to find the usability problems you imply.

**Comment by SilentSpike** [comment]
Yeah I'm working on it in a separate branch

**Comment by SilentSpike** [comment]
Mock-up done, [here's how it'd work](https://www.youtube.com/watch?v=9V0KFxnCrQ8&feature=youtu.be).

Much more simple and effective in my opinion.

**Comment by esteldunedain** [comment]
Looks good enough to try

**Comment by SilentSpike** [comment]
It was a lot easier to implement and much easier to use. Currently it's an extension of the interact_menu addon (as I figured it made more sense in this more focused state), do you think it should be implemented as a separate one?

For documentation:
* It complies from `ACE_ZeusActions` in the config.
* It uses the interact button to open
* Has the side effect of allowing self interaction in zeus view

@jaynus would also be interested to hear your thoughts.
